// Database types for ADHDBuddy
// This file will be auto-generated by `supabase gen types` in production
// For now, we define types based on our schema

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          name: string | null;
          avatar_url: string | null;
          timezone: string;
          created_at: string;
        };
        Insert: {
          id: string;
          name?: string | null;
          avatar_url?: string | null;
          timezone?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          name?: string | null;
          avatar_url?: string | null;
          timezone?: string;
          created_at?: string;
        };
      };
      sessions: {
        Row: {
          id: string;
          start_time: string;
          duration_minutes: number;
          status: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          start_time: string;
          duration_minutes: number;
          status?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          start_time?: string;
          duration_minutes?: number;
          status?: string;
          created_at?: string;
        };
      };
      session_participants: {
        Row: {
          id: string;
          session_id: string;
          user_id: string;
          goal: string | null;
          goal_completed: boolean | null;
          joined_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          session_id: string;
          user_id: string;
          goal?: string | null;
          goal_completed?: boolean | null;
          joined_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          session_id?: string;
          user_id?: string;
          goal?: string | null;
          goal_completed?: boolean | null;
          joined_at?: string | null;
          created_at?: string;
        };
      };
      user_preferences: {
        Row: {
          user_id: string;
          notifications_enabled: boolean;
          preferred_duration: number;
          is_premium: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          user_id: string;
          notifications_enabled?: boolean;
          preferred_duration?: number;
          is_premium?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          user_id?: string;
          notifications_enabled?: boolean;
          preferred_duration?: number;
          is_premium?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      user_connections: {
        Row: {
          id: string;
          user_id: string;
          connected_user_id: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          connected_user_id: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          connected_user_id?: string;
          created_at?: string;
        };
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
  };
}
